### ISSUE TITLE
FYI: NMEA2000_can2040 (and thx)

### ISSUE THREAD

**Issue by speters** [KevinOConnor/can2040#29]
Hi Kevin,
thanks for your great code!

I used it to create [NMEA2000_can2040](https://github.com/speters/NMEA2000_can2040) as a driver library for the excellent [NMEA2000 library by Timo Lappalainen](https://github.com/ttlappalainen/NMEA2000)[^1].
In case you might look at my code, bear with me, as I am not proficient in C++ - it is fine for me if it works. I head no special project in mind, but found it interesting to get some of Timo's examples running on an RP2040.

I also saw _CAN2040_  used in [Klipper CanBoot](https://github.com/Arksine/CanBoot) and really like the idea. A lot of commercial NMEA2000 manufacturers offer firmware update possibilities via NMEA2000/CAN, but there is no standard way (hope someone will eventually share some logged data with the [CanBoat project](https://github.com/canboat/canboat) to show how things work).

With kind regards from Hamburg,
Sönke Peters

[^1]: NMEA2000 is a CAN standard for instrument data on (sailing, motor, leisure) boats.  Its standard is "protected" by an organisation with hefty membership fees, so free implementations must rely mainly on sniffed data, and scarce documentation snippets of manufacturers.

**Comment by KevinOConnor** [comment]
Thanks for sharing!

-Kevin
