### ISSUE TITLE
Example code fixes

### ISSUE THREAD

**Issue by sailingfree** [KevinOConnor/can2040#3]
Hi, thanks for an excellent driver for the pico. Just one small issue in the API document. I think the example code should read:

`// Enable irqs`
`    irq_set_exclusive_handler(PIO0_IRQ_0_IRQn, PIOx_IRQHandler);`

The irq_set_exclusive_handler has the arguments swapped.

**Comment by sailingfree** [comment]
Sorry, your example is right, the official SDK uses 'PIO0_IRQ_0_IRQn'.

**Comment by KevinOConnor** [comment]
Thanks.  Should be fixed now (commit 6355c1bc).

-Kevin
