### ISSUE TITLE
Recovery when an error occurs

### ISSUE THREAD

**Issue by furusawata** [KevinOConnor/can2040#35]
Hello Kevin

I am writing a program using can2040.
An error is intentionally generated at the time of transmission and reception, and the behavior is confirmed.
If an error occurs during transmission, recovery is not possible.

I also tested it with Klipper.
`cangen can0 -g 2 -e -I 00EF0102 -L 8 -D 0000000000000000`
It stops when an error is generated on purpose.

![scope_17](https://user-images.githubusercontent.com/22042592/234184254-8ad578c9-a8cc-4cf3-aeb8-2c3c6dffdf3a.png)
The command stops and prints the following comment:
`write: No buffer space available`
After this I can't restore without unplugging and plugging the USB.

Can I restart with can2040 software?

**Comment by KevinOConnor** [comment]
I'm not sure what you are reporting.  If there is a situation where can2040 is not doing the right thing, I'd need to be able to setup a test environment here to reproduce the problem.  Can you describe your test hardware and the steps needed to reproduce the problem?

-Kevin

**Comment by furusawata** [comment]
The following configurations have been tested.

![system](https://user-images.githubusercontent.com/22042592/234449661-2ab15b71-52be-436c-84ad-60edb8c51955.png)

Packets are sent from A to C or B to C.

The following is the waveform under normal conditions.

![scope_20](https://user-images.githubusercontent.com/22042592/234442803-b58aa28d-044d-47c7-bc20-b08e34e5e1eb.png)

PCAN-USB can error on any bit.

![PCAN](https://user-images.githubusercontent.com/22042592/234443973-6212128c-7640-45dd-8497-6f83cb8bc57d.png)

When an error is made from B to C, it is resent.

![scope_21](https://user-images.githubusercontent.com/22042592/234443280-747fb0d9-1c3e-4456-8c1b-c5041cc5b78d.png)

However, it does not resend when an error is generated from A to C.

![scope_19](https://user-images.githubusercontent.com/22042592/234443605-a7f2e6ff-ab4b-4c27-879f-4f52df8e3355.png)


Is there a problem with my can2040 usage?
Is there a way for you to raise the error?
Is there anything else to check?

**Comment by KevinOConnor** [comment]
Okay I think I understand.  You are reporting that if another node sends an error frame while can2040 is transmitting then can2040 stops functioning.

I don't have a hardware setup readily available to reproduce this.  However, I've seen lots of cases where can2040 correctly responds to an error frame.  So, this sounds like a regression or something specific to the timing of the error frame.

What version of can2040 are you using?

Have you tried running an older version of can2040 to see if it has the same behavior (for example the v1.3.0 tag or v0.2.0 tag of can2040)?

Does injecting the error frame at a different bit location (eg, bit 20 instead of 60) alter the outcome of the test?

I'll see if I can setup a test environment locally.

-Kevin

**Comment by furusawata** [comment]
I tried changing the bit location.
Bit101 and below were not resent, and bit102 and above were resent.

![bit_101_102](https://user-images.githubusercontent.com/22042592/234474135-650f5000-7ed2-4d51-970f-0744dc757bf0.png)

There was no difference between versions.

- master
- work-txtiming-20230313
- can2040-1.3.0
- can2040-0.2.0

Regards,

**Comment by KevinOConnor** [comment]
You have very nice test equipment.

I was able to reproduce this problem locally.  It appears the can2040 code has a defect in how it detects "tx conflict" conditions.

I have a proposed fix at #36.

Thank you for reporting this issue.
-Kevin

**Comment by furusawata** [comment]
Thanks for the fix.
Confirmed to resend.

Could you also fix work-txtiming-20230313(#32)?

**Comment by KevinOConnor** [comment]
Great.

Sure, I rebased #32 on top of #36.

-Kevin

**Comment by furusawata** [comment]
Thank you!

**Comment by KevinOConnor** [comment]
I committed PR #36.

-Kevin
