### ISSUE TITLE
Pico stops sending can message halfway through, then retries

### ISSUE THREAD

**Issue by Nate711** [KevinOConnor/can2040#43]
Hi, I was having no problems when talking between two can transceivers connected to the same pico, but now when I talk to an external device (mg4005 can bus bldc motor), the Pico seems to try to send a message, fails halfway, then retries successfully. Any idea what's going on? Thanks!

<img width="1095" alt="Screenshot 2023-06-12 at 10 42 55 PM" src="https://github.com/KevinOConnor/can2040/assets/1295426/7a04e801-5946-46f7-bc68-e6e95969e60e">

**Comment by KevinOConnor** [comment]
That certainly looks odd.  Make sure you are on the very latest can2040 code as there were some recent changes to the handling of transmit messages.

-Kevin

**Comment by Nate711** [comment]
Thanks for the response Kevin! I just checked and I'm using the latest main. It seems like I'm able to change how often these errors occur by changing the delay between sending messages. For instance, if I delay 200us between sending two CAN messages, the error rate seems to be low, like 1 in 10. However if I change that to 300us, it becomes maybe 1 in 2. Btw, the code I'm running is this: https://github.com/Nate711/can2040-test/blob/main/apps/mg4005_test.cc

**Comment by Nate711** [comment]
I resolved one issue: In addition to the half-formed can messages, the pico would often (~1 in 3 times) repeat even a successfully sent and ACKd message (see below). I fixed this by just removing my print statement that happened every time CAN messages were sent. Oops! I didn't realize the USB comms would add irq latency. Still have fix the half-formed message problem...
<img width="825" alt="Screenshot 2023-06-18 at 12 58 32 AM" src="https://github.com/KevinOConnor/can2040/assets/1295426/78455bb7-6e29-4d0c-ada5-ad6cdeb37016">

**Comment by Nate711** [comment]
Update: I removed the actuator and instead made CAN 1 talk to CAN 2 (both have transceivers) to see if the actuator was the issue. It was not. The program I used to test this sent 3 messages over can in a 1khz loop. Sometimes when I run my code, the 2nd message is repeated, but other times, the messages are totally fine. Maybe you can recreate this issue on your side. My code is: https://github.com/Nate711/can2040-test/blob/main/apps/dual_can_test.cc 
<img width="688" alt="Screenshot 2023-06-18 at 1 27 51 AM" src="https://github.com/KevinOConnor/can2040/assets/1295426/c65cac17-5232-4e1c-b28e-74b27ddfe6c5">
