### ISSUE TITLE
CAN2040_NOTIFY_TX received when bus disconnected

### ISSUE THREAD

**Issue by obdevel** [KevinOConnor/can2040#51]
During some experimentation, I discovered that the callback function may trigger with CAN2040_NOTIFY_TX even when the bus is physically disconnected. I had previously sent some frames and expected they'd be stuck in the output buffer. The spurious notification seems to happen unpredictably some time later, or not.

Is this due to floating inputs on the transceiver appearing to be an ack from another (non-existent) node and confusing the state machine ?

This is not a problem for me; merely a curious observation. Although the output buffer being full for some seconds could be a useful indicator of disconnection from the bus or wiring problems, by implication.

**Comment by KevinOConnor** [comment]
A transmit message notification should only occur after the message contents have been fully confirmed on the CANRX line (including header, body, crc, ack, and eof bits).  So, hard to see how line noise could cause that.

I'd guess a trace of the CANRX/CANTX lines and a log of the can2040 function calls would be needed to figure out what happened.

Cheers,
-Kevin
