### ISSUE TITLE
Can can2040_start be called more than once?

### ISSUE THREAD

**Issue by jhifte** [KevinOConnor/can2040#52]
If I want to change the baudrate after calling can2040_start the first time, is it safe to call the function a second time, with different parameters? Or should I stop the statemachine or even call can2040_setup again before that?

**Comment by KevinOConnor** [comment]
It is valid to call `can2040_start()` after `can2040_stop()` - see the documentation at: https://github.com/KevinOConnor/can2040/blob/master/docs/API.md#can2040_stop

-Kevin

**Comment by jhifte** [comment]
Thanks, I knew it had to be something I overlooked.
